name: Deploy

on:
  push:
    branches:
      - main
    # note this would trigger a deploy if tagging an old release too
    tags:
    - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: git config
      run: |
        git config user.name github-pages-deploy-action
        git config user.email github-pages-deploy-action@@users.noreply.github.com
        git remote set-url origin https://${{github.actor}}:${{github.token}}@github.com/${{github.repository}}.git
    - run: yarn install
    - run: REACT_APP_GIT_DESCRIBE=$(git describe --always) yarn deploy
